### PR TITLE
add robot specific information on rosparam

### PR DESCRIPTION
**Pull request by k-okada**
please see https://github.com/ros-infrastructure/rep/pull/104 for the background,
since we have several robots and would like to have common interface for getting robot type/names

### CODE REVIEW

**Review by moriarty — APPROVED** [review]
LGTM. @cjds should this be tested?

Also, it should go into indigo-devel, and melodic-devel.
ATM: Melodic devel hasn't diverged from indigo-devel but it will with #24 so we should merge this before really branching off melodic-devel

**Comment by moriarty** [comment]
I just noticed the ros-infrastructure/rep#104 is still an open PR, but it seems reasonable, I think we could merge this without that becoming an official standard, but then I guess it only needs to go into the `melodic-devel` branch.

**Review by cjds — APPROVED** [review]
@moriarty tested already and LGTM

**Comment by moriarty** [comment]
@k-okada Thanks for the PR!

@cjds I squash & merged to indigo-devel, because that’s where the original PR was opened for, and we still need to release the rest of the melodic stuff.

We can just move melodic-devel branch ahead to include this commit.

**Pull request merged**
